/** @format */

import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
import { cn } from "../lib/utils";
import SideNavbar from "~/components/sidenav";
import TopNav from "./top-nav";
import Footer from "./footer";
import { Toaster } from "~/components/ui/toaster"
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <div lang="en">
      <div
        className={cn(
          " w-full   bg-white text-black  ",
          // inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        <TopNav />
        
        <div className="flex bg-[#F8FAFA]">
        <SideNavbar />
        
        <div  style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }} className="p-8 h-[100vh] max-h-[562px] bg-[#F8FAFA] overflow-y-auto scrollbar-width-0 w-full">{children}</div>
        </div>
        <Toaster />
        <Footer />
      </div>
    </div>
  );
}